name: Release Workflow

on:
  workflow_run:
    workflows: ["CI (Continuous Integration)"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Git Config
      run: |
        git config --global user.email "zerkxubas@gmail.com"
        git config --global user.name "Subash Sharma"
        git config --list  # Add this line for debugging

    - name: Fetch tags
      run: git fetch --tags

    - name: Bump version and create tag
      id: tag_version
      run: |
        current_version=$(git describe --tags `git rev-list --tags --max-count=1`)
        if [ -z "$current_version" ]; then
          new_version="v1.0.0"
        else
          new_version=$(echo $current_version | awk -F. '{printf "v%d.%d.%d", $1, $2, $3+1}')
        fi
        git tag $new_version
        git push origin $new_version

      # Handle cases where no tags exist yet
      continue-on-error: true

    - name: Create GitHub release
      if: ${{ success() }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_version }}
        name: ${{ steps.tag_version.outputs.new_version }}
        body: "Automated release ${{ steps.tag_version.outputs.new_version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}